import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, relative } from 'path';
import { globSync } from 'glob';
import { loadConfig } from './config';
import { registerFunctions } from './register';

export function discoverFunctionFilesSync(
  projectRoot: string,
  pattern: string,
): string[] {
  const files = globSync(pattern, { cwd: projectRoot, absolute: true });

  return files.filter((file) => {
    const content = readFileSync(file, 'utf-8');
    return content.includes('@pingback/next');
  });
}

// Keep async version for tests
export async function discoverFunctionFiles(
  projectRoot: string,
  pattern: string,
): Promise<string[]> {
  return discoverFunctionFilesSync(projectRoot, pattern);
}

export function generateRouteFile(
  projectRoot: string,
  routePath: string,
  functionFiles: string[],
): void {
  const routeDir = join(projectRoot, 'app', ...routePath.split('/').filter(Boolean));
  mkdirSync(routeDir, { recursive: true });

  const routeFilePath = join(routeDir, 'route.ts');
  const relativeToRoute = (absPath: string) => {
    const rel = relative(routeDir, absPath);
    return rel.replace(/\.(ts|js)$/, '');
  };

  const imports = functionFiles
    .map((f) => `import "${relativeToRoute(f)}";`)
    .join('\n');

  const content = `// AUTO-GENERATED BY @pingback/next — do not edit
import { createRouteHandler } from "@pingback/next/handler";
${imports}

export const POST = createRouteHandler();
`;

  writeFileSync(routeFilePath, content);
}

let routeGenerated = false;

export function withPingback(nextConfig: any = {}): any {
  const originalWebpack = nextConfig.webpack;

  // Generate route file synchronously BEFORE webpack runs
  // This ensures the route exists when Next.js compiles pages
  if (!routeGenerated) {
    try {
      const projectRoot = process.cwd();
      const configPath = join(projectRoot, 'pingback.config.ts');
      const configPathJs = join(projectRoot, 'pingback.config.js');

      if (existsSync(configPath) || existsSync(configPathJs)) {
        // Read config defaults manually (can't async import here)
        const functionsDir = 'lib/pingback/**/*.{ts,js}';
        const routePath = '/api/__pingback';

        const files = discoverFunctionFilesSync(projectRoot, functionsDir);
        if (files.length > 0) {
          console.log(`[pingback] Found ${files.length} function file(s)`);
          generateRouteFile(projectRoot, routePath, files);
          console.log(`[pingback] Generated route handler at app${routePath}/route.ts`);

          const routeDir = `app${routePath}`;
          const gitignorePath = join(projectRoot, '.gitignore');
          if (existsSync(gitignorePath)) {
            const gitignore = readFileSync(gitignorePath, 'utf-8');
            if (!gitignore.includes(routeDir)) {
              console.warn(`[pingback] Warning: Add "${routeDir}" to your .gitignore`);
            }
          }
        }
      }
      routeGenerated = true;
    } catch (err) {
      console.error(`[pingback] Route generation failed: ${(err as Error).message}`);
    }
  }

  let registrationPromise: Promise<void> | null = null;

  return {
    ...nextConfig,
    webpack(config: any, context: any) {
      // Only register with platform during production server builds
      if (context.isServer && !context.dev && !registrationPromise) {
        registrationPromise = runRegistration(context.dir).catch((err: Error) => {
          console.error(`[pingback] Registration failed: ${err.message}`);
        });

        config.plugins.push({
          apply(compiler: any) {
            compiler.hooks.afterEmit.tapPromise('PingbackRegistration', async () => {
              if (registrationPromise) await registrationPromise;
            });
          },
        });
      }

      if (originalWebpack) {
        return originalWebpack(config, context);
      }
      return config;
    },
  };
}

async function runRegistration(projectRoot: string): Promise<void> {
  const config = await loadConfig(projectRoot);
  const files = discoverFunctionFilesSync(projectRoot, config.functionsDir);

  if (files.length === 0) return;

  for (const file of files) {
    try { await import(file); } catch (err) {
      console.warn(`[pingback] Could not import ${file}: ${(err as Error).message}`);
    }
  }

  const result = await registerFunctions(config);
  console.log(`[pingback] Registered ${result.jobs.length} function(s) with platform`);
}
